name: release

on:
  workflow_dispatch: 
  push:
    tags:
      - "v*"

permissions:
  contents: write
jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build-linux-amd64

      - uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: bin/*linux-amd64*

  linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build-linux-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: bin/*linux-arm64*

  release:
    needs: [linux-amd64, linux-arm64]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "**/*"